# Web Scarping assignment 4:

In [1]:
#import the libraries
#!pip  install selenium
#!pip install webdriver_manager
# importing all required library
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.common.action_chains import ActionChains

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
`You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
#lets frist connect the web driver
driver = webdriver.Chrome("chromedriver.exe")

In [4]:
#accessing the webdriver
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(2)


#creating empty list
most_viewed_video = { }
most_viewed_video['Rank']=[]
most_viewed_video['Video Name']=[]
most_viewed_video['Uploader']=[]
most_viewed_video['Views in billion']=[]
most_viewed_video['Upload date']=[]
most_viewed_video['Note']=[]


#video rank
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]"):
    most_viewed_video['Rank'].append(i.text)
    
#video Name    
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]"):
    most_viewed_video['Video Name'].append(i.text)
    
#Uploader    
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]"):
    most_viewed_video['Uploader'].append(i.text)
    
#Views in billions    
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]"):
    most_viewed_video['Views in billion'].append(i.text)
    
#upload Date    
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]"):
    most_viewed_video['Upload date'].append(i.text)

#Note    
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[6]"):
    most_viewed_video['Note'].append(i.text)
    
    
Most_viewed_youtube_video = pd.DataFrame(most_viewed_video)
Most_viewed_youtube_video[:30]

,Rank,Video Name,Uploader,Views in billion,Upload date,Note
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.91,"June 17, 2016",[B]
1,2.,"""Despacito""[24]",Luis Fonsi,7.43,"January 12, 2017",[C]
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.53,"October 8, 2016",[D]
3,4.,"""Shape of You""[26]",Ed Sheeran,5.37,"January 30, 2017",[E]
4,5.,"""See You Again""[27]",Wiz Khalifa,5.16,"April 6, 2015",[F]
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.44,"January 31, 2012",[G]
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.26,"May 2, 2018",[H]
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.22,"February 27, 2018",[I]
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.22,"November 19, 2014",[J]
9,10.,"""Gangnam Style""[34]",Psy,4.11,"July 15, 2012",[K]
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.97,"March 6, 2014",
11,12.,"""Sugar""[37]",Maroon 5,3.50,"January 14, 2015",
12,13.,"""Sorry""[38]",Justin Bieber,3.45,"October 22, 2015",
13,14.,"""Dame Tu Cosita""[39]",El Chombo,3.43,"April 5, 2018",
14,15.,"""Roar""[40]",Katy Perry,3.38,"September 5, 2013",
15,16.,"""Counting Stars""[41]",OneRepublic,3.33,"May 31, 2013",
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.28,"October 7, 2014",
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.13,"May 24, 2018",
18,19.,"""Dark Horse""[44]",Katy Perry,3.10,"February 20, 2014",
19,20.,"""Faded""[45]",Alan Walker,3.09,"December 3, 2015",
20,21.,"""Shake It Off""[46]",Taylor Swift,3.07,"August 18, 2014",
21,22.,"""Girls Like You""[47]",Maroon 5,3.06,"May 31, 2018",
22,23.,"""Lean On""[48]",Major Lazer,3.06,"March 22, 2015",
23,24.,"""Bailando""[49]",Enrique Iglesias,3.06,"April 11, 2014",
24,25.,"""Let Her Go""[50]",Passenger,3.02,"July 25, 2012",
25,26.,"""Mi Gente""[51]",J Balvin,2.94,"June 29, 2017",
26,27.,"""Perfect""[52]",Ed Sheeran,2.89,"November 9, 2017",
27,28.,"""Waka Waka (This Time for Africa)""[53]",Shakira,2.87,"June 4, 2010",
28,29.,"""Axel F""[54]",Crazy Frog,2.86,"June 16, 2009",
29,30.,"""Hello""[55]",Adele,2.85,"October 22, 2015",

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code

In [7]:
#lets frist connect the web driver
driver = webdriver.Chrome("chromedriver.exe")

#accessing the web page 
driver.get("https://www.bcci.tv")
time.sleep(3)


#clicking on internation drop down
International = driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']") 
International.click()
time.sleep(3)

#clicking on Fixtures
Fixtures = driver.find_element_by_xpath("//div[@class='drop-down__options']/ul/li/a")
Fixtures.click()
time.sleep(3)


Criket_Matches = { }
Criket_Matches['Match Title']=[]
Criket_Matches['Series']=[]
Criket_Matches['Place']=[]
Criket_Matches['Date']=[]
Criket_Matches['Time']=[]
Criket_Matches['Month']=[]



#scraping match title 
for i in driver.find_elements_by_xpath("//Strong[@class='fixture__name fixture__name--with-margin']"):
    Criket_Matches['Match Title'].append(i.text)
    
#scarping the series 
for i in driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    Criket_Matches['Series'].append(i.text)
 
#scarping the Date
for i in driver.find_elements_by_xpath("//span[@class='fixture__date']"):
    Criket_Matches['Date'].append(i.text)
    
#scarping the Month
for i in driver.find_elements_by_xpath("//span[@class='fixture__month']"):
    Criket_Matches['Month'].append(i.text)
    
#scarping the Time   
for i in driver.find_elements_by_xpath("//span[@class='fixture__time']"):
    Criket_Matches['Time'].append(i.text)    
    
#scarping the place
for i in driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span"):
    Criket_Matches['Place'].append(i.text)
    
#creating the data frame 
Criket_Matches = pd.DataFrame(Criket_Matches)
Criket_Matches.head(10)

,Match Title,Series,Place,Date,Time,Month
0,1st ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",13,14:30 IST,JULY
1,2nd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",16,14:30 IST,JULY
2,3rd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",18,14:30 IST,JULY
3,1st T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",21,19:00 IST,JULY
4,2nd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",23,19:00 IST,JULY
5,3rd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",25,19:00 IST,JULY
6,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",04,15:30 IST,AUGUST
7,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",12,15:30 IST,AUGUST
8,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",25,15:30 IST,AUGUST
9,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02,15:30 IST,SEPTEMBER

3.Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [40]:
#lets frist connect the web driver
driver = webdriver.Chrome("chromedriver.exe")

#accessing the web page 
driver.get("https://www.guru99.com")
time.sleep(3)

#clicking on internation drop down
selenium1 = driver.find_element_by_xpath("//a[@title='Selenium']") 
selenium1.click()
time.sleep(3)

Exception = driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']") 
Exception.click()
time.sleep(3)

Excaptions={ }
Excaptions['Names'] =[]
Excaptions['description']=[]

#scarping the Exception names 
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]"):
    Excaptions['Names'].append(i.text)
    
#scarping the exception descrption
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]"):
    Excaptions['description'].append(i.text)
    

#Creating the dataframe 

Excaptions =pd.DataFrame(Excaptions)
Excaptions

,Names,description
0,Exception name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code

In [23]:
#lets frist connect the web driver
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)

#accessing the web page 
driver.get("http://statisticstimes.com")
time.sleep(3)

#clicking on Ecnomy menu
economy = driver.find_element_by_xpath("//div[@class='navbar']/div[2]/div[1]/a[3]").get_attribute('href') 
driver.get(economy)
time.sleep(3)

#selecting india GDP
gdp = driver.find_element_by_xpath("html/body/div[2]/div[2]/div[2]/ul/li/a").get_attribute('href') 
driver.get(gdp)
time.sleep(3)


States_GDP ={ }
States_GDP['Rank']=[]
States_GDP['State']=[]
States_GDP['GSDP 19-20']=[]
States_GDP['GSDP 18-19']=[]
States_GDP['Share 18-19']=[]
States_GDP['GDP $ billion']=[]
    
#Rank
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[1]"):
    try:
        States_GDP['Rank'].append(i.text)
    except:
        States_GDP['Rank'].append("-")

    
#State name
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[2]"):
    try:
        States_GDP['State'].append(i.text)
    except:
        States_GDP['State'].append("-")

        
#GSDP 19-20
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[3]"):
    try:
        States_GDP['GSDP 19-20'].append(i.text)
    except:
        States_GDP['GSDP 19-20'].append('-')
        
#GSDP 18-19
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[4]"):
    try:
        States_GDP['GSDP 18-19'].append(i.text)
    except:
        States_GDP['GSDP 18-29'].append('-')

 
#GSDP 18-19
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[5]"):
    try:
        States_GDP['Share 18-19'].append(i.text)
    except:
        States_GDP['Share 18-19'].append('-')
    
#GDP $ billion
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[6]"):
    try:
        States_GDP['GDP $ billion'].append(i.text)
    except:
        States_GDP['GDP $ billion'].append('-')
    

States_GDP = pd.DataFrame(States_GDP)
States_GDP

,Rank,State,GSDP 19-20,GSDP 18-19,Share 18-19,GDP $ billion
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [54]:
print(len(States_GDP['Rank']),len(States_GDP['State']),len(States_GDP['GSDP 19-20']),len(States_GDP['GSDP 18-19']),len(States_GDP['GDP $ billion']),len(States_GDP['Rank']))

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [ ]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(4)

In [ ]:


url ="https://github.com/"
driver.get(url)
time.sleep(7)


explore_opt = driver.find_element_by_xpath("//ul[@class='d-lg-flex list-style-none']/li[4]")
action = ActionChains(driver)
action.click_and_hold(explore_opt).perform()


trend_opt = driver.find_element_by_xpath("//ul[@class='list-style-none mb-3'][2]/li[3]/a")
action.click(trend_opt).perform()


trending_repo = {}
trending_repo['Repository_Title'] = []
trending_repo['Repository_Description'] = []
trending_repo['Contributors_Count'] = []
trending_repo['Language_Used'] = []


titles = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in titles:
    if i.text == " ":
        trending_repo['Repository_Title'].append("-")
    else:
        trending_repo['Repository_Title'].append(i.text)
time.sleep(2)

#description
count = 1
for i in range(len(driver.find_elements_by_xpath("//article[@class='Box-row']"))):
    
    try:
        descriptions = driver.find_element_by_xpath(f"//article[@class='Box-row'][{count}]/p[1]")
        trending_repo['Repository_Description'].append(descriptions.text) 
        
    except NoSuchElementException:
        trending_repo['Repository_Description'].append("-")
    
    count += 1

#contributor_counts
contributor_counts = driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']/a[2]")
for i in contributor_counts:
    if i.text == "":
        trending_repo['Contributors_Count'].append("-")
    else:
        trending_repo['Contributors_Count'].append(i.text)
time.sleep(2)

#language
lan_count = 1
for i in range(len(driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']"))):
    try:
        langu = driver.find_element_by_xpath(f"//article[@class='Box-row'][{lan_count}]/div[2]/span/span[2]")
        trending_repo['Language_Used'].append(langu.text) 
        
    except NoSuchElementException:
        trending_repo['Language_Used'].append("-")
    lan_count += 1
time.sleep(2)


#creating dataframe
Trending_repositories = pd.DataFrame(trending_repo)
Trending_repositories.to_csv("Trending repositories.csv")
Trending_repositories.head()

ElementNotInteractableException: Message: element not interactable: https://github.com/trending has no size and location
  (Session info: chrome=91.0.4472.124)

6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(4)

In [3]:
driver.get("https://www.billboard.com")
time.sleep(4)

chart = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]/a")
action = ActionChains(driver)
action.click_and_hold(chart).perform()
#clicking trending option
Hot_100 = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]/span/span/span/span[1]/ul/li[1]/a")
action.click(Hot_100).perform()

In [29]:
BillBoard_hot_100 ={}
BillBoard_hot_100['Rank']=[]
BillBoard_hot_100['Song Name'] =[]
BillBoard_hot_100['Artist Name'] =[]
BillBoard_hot_100['Last week'] =[]
BillBoard_hot_100['Peak'] =[]
BillBoard_hot_100['Weeks on chart'] =[]


for i in driver.find_elements_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li/button/span[2]/span[1]"):
    BillBoard_hot_100['Song Name'].append(i.text)
        

for i in driver.find_elements_by_xpath(f"/html/body/main/div/div/div[7]/div/ol/li/button/span[2]/span[2]"):
    BillBoard_hot_100['Artist Name'].append(i.text)
        
for i in driver.find_elements_by_xpath("/html/body/main/div/div/div[7]/div/ol/li/button/span[1]/span[1]"):
    BillBoard_hot_100['Rank'].append(i.text)   

        
for i in driver.find_elements_by_xpath("//*[@id='charts']/div/div[7]/div/ol/li/button/div/div[2]"):
    BillBoard_hot_100['Last week'].append(i.text)
        
for i in driver.find_elements_by_xpath("//*[@id='charts']/div/div[7]/div/ol/li/button/div/div[2]"):
    BillBoard_hot_100['Peak'].append(i.text)
    
    
for i in driver.find_elements_by_xpath('//*[@id="charts"]/div/div[7]/div/ol/li/button/div/div[3]'):
    BillBoard_hot_100['Weeks on chart'].append(i.text)
    
BillBoard_hot_100 = pd.DataFrame(BillBoard_hot_100)

BillBoard_hot_100

,Rank,Song Name,Artist Name,Last week,Peak,Weeks on chart
0,1,Butter,BTS,1,1,7
1,2,Good 4 U,Olivia Rodrigo,2,2,1
2,3,Levitating,Dua Lipa Featuring DaBaby,2,2,40
3,4,Kiss Me More,Doja Cat Featuring SZA,3,3,13
4,5,Montero (Call Me By Your Name),Lil Nas X,8,8,1
5,6,Bad Habits,Ed Sheeran,5,5,2
6,7,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),1,1,18
7,8,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,1,1,16
8,9,Save Your Tears,The Weeknd & Ariana Grande,1,1,30
9,10,Deja Vu,Olivia Rodrigo,3,3,14
10,11,Astronaut In The Ocean,Masked Wolf,6,6,21
11,12,Rapstar,Polo G,1,1,13
12,13,You Right,Doja Cat & The Weeknd,11,11,2
13,14,Am I The Only One,Aaron Lewis,-,-,14
14,15,Blinding Lights,The Weeknd,1,1,83
15,16,Without You,The Kid LAROI,8,8,31
16,17,Thot Shit,Megan Thee Stallion,16,16,4
17,18,Forever After All,Luke Combs,2,2,37
18,19,Heartbreak Anniversary,Giveon,20,20,16
19,20,Fancy Like,Walker Hayes,34,34,20
20,21,Every Chance I Get,DJ Khaled Featuring Lil Baby & Lil Durk,28,28,20
21,22,Famous Friends,Chris Young + Kane Brown,21,21,21
22,23,Beautiful Mistakes,Maroon 5 Featuring Megan Thee Stallion,13,13,18
23,24,Best Friend,Saweetie Featuring Doja Cat,14,14,26
24,25,Lil Bit,Nelly & Florida Georgia Line,23,23,16
25,26,Single Saturday Night,Cole Swindell,53,53,26
26,27,Heat Waves,Glass Animals,19,19,25
27,28,Leave Before You Love Me,Marshmello X Jonas Brothers,31,31,28
28,29,Wants And Needs,Drake Featuring Lil Baby,2,2,18
29,30,Yonaguni,Bad Bunny,10,10,5
...,...,...,...,...,...,...
70,71,Country Again,Thomas Rhett,86,86,71
71,72,Fiel,"Los Legendarios, Wisin & Jhay Cortez",62,62,4
72,73,Renegade,Big Red Machine Featuring Taylor Swift,-,-,73
73,74,Waves,Luke Bryan,94,94,74
74,75,We Didn't Have Much,Justin Moore,87,87,75
75,76,Minimum Wage,Blake Shelton,67,67,9
76,77,Follow You,Imagine Dragons,68,68,14
77,78,"Jealousy, Jealousy",Olivia Rodrigo,24,24,7
78,79,Come Through,H.E.R. Featuring Chris Brown,91,91,64
79,80,Twerkulator,City Girls,96,96,51
80,81,Cry No More,G Herbo Featuring Polo G & Lil Tjay,-,-,81
81,82,Essence,Wizkid Featuring Tems,-,-,82
82,83,A-O-K,Tai Verdes,-,-,83
83,84,4 Da Gang,42 Dugg & Roddy Ricch,67,67,13
84,85,Tombstone,Rod Wave,11,11,15
85,86,Made For You,Jake Owen,32,32,20
86,87,Having Our Way,Migos Featuring Drake,15,15,4
87,88,My Boy,Elvie Shane,-,-,88
88,89,transparentsoul,Willow Featuring Travis Barker,76,76,4
89,90,You Should Probably Leave,Chris Stapleton,-,-,90
90,91,I Was On A Boat That Day,Old Dominion,-,-,91
91,92,Outside,MO3 X OG Bobby Billions,-,-,92
92,93,Working,Tate McRae X Khalid,93,93,3
93,94,Miss The Rage,Trippie Redd & Playboi Carti,11,11,9
94,95,Cold Beer Calling My Name,Jameson Rodgers Featuring Luke Combs,-,-,95
95,96,All I Know So Far,P!nk,-,-,74
96,97,What's Next,Drake,-,-,1
97,98,Enough For You,Olivia Rodrigo,-,-,14
98,99,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
99,100,Tell Em,Cochise & $NOT,-,-,64

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
click on search. All this should be done through code

In [102]:
driver.get("https://www.naukri.com")
time.sleep(4)

#accessing the recuiter page
reciuters = driver.find_element_by_xpath("//*[@id='root']/div[1]/div/ul[1]/li[2]/a").get_attribute('href')
driver.get(reciuters)
time.sleep(2)



#input from user
job = input("Enter the job designation:") 

search = driver.find_element_by_xpath('//*[@id="skill"]/div[1]/div[2]/input')
search.send_keys(job)

btn = driver.find_element_by_xpath("//*[@id='qsbFormBtn']")
btn.click()

#Creating empty list 
Recuiters={ }
Recuiters['Name'] = []
Recuiters['Company'] = []
Recuiters['Designation'] = []
Recuiters['Skills'] = []
Recuiters['Location'] = []



for i in driver.find_elements_by_xpath("/html/body/div[3]/div/div/div/div/div/div/div/div/p/span/small"):
    Recuiters['Location'].append(i.text)
else:
    Recuiters['Location'].append('-')
       
for i in driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div/div/p/a[1]/span"):
    Recuiters['Name'].append(i.text)
    
for i in driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div/div/p/a[2]"):
    Recuiters['Company'].append(i.text)
    
for i in driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div/div/p/span[1]"):
    Recuiters['Designation'].append(i.text)
    
for i in driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div/div/div[2]"):
    Recuiters['Skills'].append(i.text)
    
      
    
Recuiters['Name'] = Recuiters['Name'][:49]
Recuiters['Company'] =  Recuiters['Company'][:49]
Recuiters['Designation'] =  Recuiters['Designation'][:49]
Recuiters['Skills'] =  Recuiters['Skills'][:49]
Recuiters['Location'] =  Recuiters['Location'][:49]
Recuiters = pd.DataFrame(Recuiters)
Recuiters

,Name,Company,Designation,Skills,Location
0,Aakash Harit,Data Science Network,HR Manager,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Shore Infotech India Pvt. Ltd,Company Recruiter,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,MARSIAN Technologies LLP,Company HR,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Enerlytics Software Solutions Pvt Ltd,Company Recruiter,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,LibraryXProject,Founder CEO,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Apidel Technologies Division of Transpower,Recruitment Lead Consultant,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,IFMR,Programme Manager,Data Science,Chennai
7,Balu Ramesh,Techvantage Systems Pvt Ltd,HR Administrator,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Weupskill- Live Wire India,Director,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,CBL Data Science Private Limited,Human Resource,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Innominds Software,Executive Hiring,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,MoneyTap,Company HR,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,QuantMagnum Technologies Pvt. Ltd.,Company HR,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Bristlecone India Ltd,Senior Executive Talent Acquisition,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,SocialPrachar.com,HR Team Lead,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,BISP Solutions,HR Manager,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,Easi Tax,HR Executive,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Novelworx Digital Solutions,Manager Talent Acquisition,Data Science,Cochin
18,Rashmi Bhattacharjee,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,HR Head,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,FirstTech Consaltants Pvt.Ltd,HR MANAGER,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,Affine Analytics,HR Recruiter,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Azahar Shaikh,NEAL ANALYTICS SERVICES PVT LTD,Company Recruiter,"Data Science, Artificial Intelligence, Machine...",Pune
22,Sandhya Khandagale,Compumatrice Multimedia Pvt Ltd,HR Recruiter,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Exela Technologies,Manager Human Resources,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Manas,Autumn Leaf Consulting Services Private...,Lead Talent acquisition,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,trainin,Proprietor,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,Nanoprecise Sci Corp,CEO,"Signal Processing, Machine Learning, Neural Ne...",Delhi
27,Rajat Kumar,R.S Consultancy &amp; Services,Founder CEO,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
28,Priya Khare,Independent Consultant,Senior Manager,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Confidential,Company Recruitment Head,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
30,Jayanth N,"Dollarbird Information Services Pvt, Ltd",Project Manager,"Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
31,SREEDHAR,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Recruitment Consultant,"Data Science, Machine Learning, Big Data Analy...",Bengaluru / Bangalore
32,Radha Manivasagam,Techcovery,HR Executive,"Python, Artificial Intelligence, Machine Learn...",Ghaziabad
33,Ravi Dubey,HyrEzy Talent Solutions LLP,Recruitment Manager,Walmart Interra Skeps Expressstores indifi whi...,Noida
34,Prateek Kumar,Trisect,Head,"Java, Python, Angularjs, Software Testing, Mac...",New Delhi
35,Amit Sharma,ASCO consulting,Consultant,"Machine Learning, Artificial Intelligence, Dat...",Chennai
36,Kanan,NY INST,senior technology instructor,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
37,Shashikant Chaudhary,3D India Staffing Research &amp; Consulting...,HR Recruiter/HR Excutive,"Relationship Management, Retail Sales, Private...",Salt Lake City
38,Brad,O.C. Tanner,"Manager, Technical Recruiting","Data Science, Software Engineering",Pune
39,Rutuja Pawar,Demand Matrix,Technical Recruiter,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
40,Madhusudhan Sridhar,MADHUSUDHAN SRIDHAR,Erp Implementer,"Data Science, Recruitment, Salary",Mumbai
41,Ankit Sinha,Suntech Global,Head Analytics,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
42,Gaurav Chouhan,Strategic Consulting Lab,Chief Technical Officer,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
43,Rashi Kacker,Impel Labs Pvt. Ltd.,Sr Product Manager,"Data Science, Node.js, Angularjs",MYSORE
44,Ashwini,MRP Advisers,Director Global Delivery,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
45,Balaji Kolli,Saras Solutions India Pvt Ltd,Co Founder,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
46,Rajani Nagaraj,WildJasmine,HR Manager,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
47,ROHIT Kumar,LNT Private Limited,Architect,"Software Development, Core Java, Unit Testing,...",Noida
48,Amir Chowdhury,Granular.ai,Managing Partner,"Machine Learning, Data Science, Product Manage...",-

In [98]:
print(len(Recuiters['Name']),len(Recuiters['Company']),len(Recuiters['Designation']),len(Recuiters['Skills']),len(Recuiters['Location']))

50 50 50 50 49

8. Scrape the details of Highest selling novels.
Url =https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [13]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
time.sleep(4)

In [29]:
Best_selling_book ={}

Best_selling_book['Book Name']= []
Best_selling_book['Author Name'] = []
Best_selling_book['Volumes sold'] =[]
Best_selling_book['Publisher']=[]
Best_selling_book['Genre']=[]


for i in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[2]"):
    Best_selling_book['Book Name'].append(i.text)
    
for i in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[3]"):
    Best_selling_book['Author Name'].append(i.text)
    
for i in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[4]"):
    Best_selling_book['Volumes sold'].append(i.text)
    
for i in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[5]"):
    Best_selling_book['Publisher'].append(i.text)
    
for i in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[6]"):
    Best_selling_book['Genre'].append(i.text)

In [34]:
Best_selling_book=pd.DataFrame(Best_selling_book)
Best_selling_book

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
5,Harry Potter and the Goblet of Fire,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
6,Harry Potter and the Chamber of Secrets,"Rowling, J.K.","3,484,047",Bloomsbury,Children's Fiction
7,Harry Potter and the Prisoner of Azkaban,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
8,Angels and Demons,"Brown, Dan","3,193,946",Transworld,"Crime, Thriller & Adventure"
9,Harry Potter and the Half-blood Prince:Childre...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction
10,Fifty Shades Darker,"James, E. L.","2,479,784",Random House,Romance & Sagas
11,Twilight,"Meyer, Stephenie","2,315,405","Little, Brown Book",Young Adult Fiction
12,"Girl with the Dragon Tattoo,The:Millennium Tri...","Larsson, Stieg","2,233,570",Quercus,"Crime, Thriller & Adventure"
13,Fifty Shades Freed,"James, E. L.","2,193,928",Random House,Romance & Sagas
14,"Lost Symbol,The","Brown, Dan","2,183,031",Transworld,"Crime, Thriller & Adventure"
15,New Moon,"Meyer, Stephenie","2,152,737","Little, Brown Book",Young Adult Fiction
16,Deception Point,"Brown, Dan","2,062,145",Transworld,"Crime, Thriller & Adventure"
17,Eclipse,"Meyer, Stephenie","2,052,876","Little, Brown Book",Young Adult Fiction
18,"Lovely Bones,The","Sebold, Alice","2,005,598",Pan Macmillan,General & Literary Fiction
19,"Curious Incident of the Dog in the Night-time,The","Haddon, Mark","1,979,552",Random House,General & Literary Fiction
20,Digital Fortress,"Brown, Dan","1,928,900",Transworld,"Crime, Thriller & Adventure"
21,"Short History of Nearly Everything,A","Bryson, Bill","1,852,919",Transworld,Popular Science
22,"Girl Who Played with Fire,The:Millennium Trilogy","Larsson, Stieg","1,814,784",Quercus,"Crime, Thriller & Adventure"
23,Breaking Dawn,"Meyer, Stephenie","1,787,118","Little, Brown Book",Young Adult Fiction
24,"Very Hungry Caterpillar,The:The Very Hungry Ca...","Carle, Eric","1,783,535",Penguin,Picture Books
25,"Gruffalo,The","Donaldson, Julia","1,781,269",Pan Macmillan,Picture Books
26,Jamie's 30-Minute Meals,"Oliver, Jamie","1,743,266",Penguin,Food & Drink: General
27,"Kite Runner,The","Hosseini, Khaled","1,629,119",Bloomsbury,General & Literary Fiction
28,One Day,"Nicholls, David","1,616,068",Hodder & Stoughton,General & Literary Fiction
29,"Thousand Splendid Suns,A","Hosseini, Khaled","1,583,992",Bloomsbury,General & Literary Fiction
...,...,...,...,...,...
70,Stupid White Men:...and Other Sorry Excuses fo...,"Moore, Michael","963,353",Penguin,Current Affairs & Issues
71,"Interpretation of Murder,The","Rubenfeld, Jed","962,515",Headline,"Crime, Thriller & Adventure"
72,Sharon Osbourne Extreme:My Autobiography,"Osbourne, Sharon","959,496","Little, Brown Book",Autobiography: The Arts
73,"Alchemist,The:A Fable About Following Your Dream","Coelho, Paulo","956,114",HarperCollins,General & Literary Fiction
74,At My Mother's Knee ...:and Other Low Joints,"O'Grady, Paul","945,640",Transworld,Autobiography: The Arts
75,Notes from a Small Island,"Bryson, Bill","931,312",Transworld,Travel Writing
76,"Return of the Naked Chef,The","Oliver, Jamie","925,425",Penguin,Food & Drink: General
77,Bridget Jones: The Edge of Reason,"Fielding, Helen","924,695",Pan Macmillan,General & Literary Fiction
78,Jamie's Italy,"Oliver, Jamie","906,968",Penguin,National & Regional Cuisine
79,I Can Make You Thin,"McKenna, Paul","905,086",Transworld,Fitness & Diet
80,Down Under,"Bryson, Bill","890,847",Transworld,Travel Writing
81,"Summons,The","Grisham, John","869,671",Random House,"Crime, Thriller & Adventure"
82,Small Island,"Levy, Andrea","869,659",Headline,General & Literary Fiction
83,Nigella Express,"Lawson, Nigella","862,602",Random House,Food & Drink: General
84,Brick Lane,"Ali, Monica","856,540",Transworld,General & Literary Fiction
85,"Memory Keeper's Daughter,The","Edwards, Kim","845,858",Penguin,General & Literary Fiction
86,Room on the Broom,"Donaldson, Julia","842,535",Pan Macmillan,Picture Books
87,About a Boy,"Hornby, Nick","828,215",Penguin,General & Literary Fiction
88,My Booky Wook,"Brand, Russell","820,563",Hodder & Stoughton,Autobiography: The Arts
89,"God Delusion,The","Dawkins, Richard","816,907",Transworld,Popular Science
90,"""Beano"" Annual,The",0,"816,585",D.C. Thomson,Children's Annuals
91,White Teeth,"Smith, Zadie","815,586",Penguin,General & Literary Fiction
92,"House at Riverton,The","Morton, Kate","814,370",Pan Macmillan,General & Literary Fiction
93,"Book Thief,The","Zusak, Markus","809,641",Transworld,General & Literary Fiction
94,Nights of Rain and Stars,"Binchy, Maeve","808,900",Orion,General & Literary Fiction
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com. 
  Url =  https://www.imdb.com/list/ls095964455/ 
 You have to find the following details: 
A) Name 
B) Year span 
C) Genre 
D) Run time 
E) Ratings 
F) Votes

In [80]:
driver.get("https://www.imdb.com/list/ls095964455/")
time.sleep(4)


Most_watched_TV_shows ={ }
Most_watched_TV_shows['Name']= []
Most_watched_TV_shows['Year span']= []
Most_watched_TV_shows['Genre']= []
Most_watched_TV_shows['Run time']= []
Most_watched_TV_shows['Ratings']= []
Most_watched_TV_shows['Votes']= []



Names = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div/h3/a")
for i in Names:
    if i.text is None:
        Most_watched_TV_shows['Name'].append("-")
    else:
        Most_watched_TV_shows['Name'].append(i.text)
        

year = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div/h3/span[2]")
for i in year:
    if i.text is None:
        Most_watched_TV_shows['Year span'].append("-")
    else:
        Most_watched_TV_shows['Year span'].append(i.text)
        
Genre = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div/p/span[5]")
for i in Genre:
    if i.text is None:
        Most_watched_TV_shows['Genre'].append("-")
    else:
        Most_watched_TV_shows['Genre'].append(i.text)
        
Run = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div/p/span[3]")
for i in Run:
    if i.text is None:
        Most_watched_TV_shows['Run time'].append("-")
    else:
        Most_watched_TV_shows['Run time'].append(i.text)
        
Ratings = driver.find_elements_by_xpath("//*[@id='main']/div/div[3]/div[3]/div/div/div/div/span[2]")
for i in Ratings:
    if i.text is None:
        Most_watched_TV_shows['Ratings'].append("-")
    else:
        Most_watched_TV_shows['Ratings'].append(i.text)
                


Votes = driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]")
for i in Votes:
    if i.text is None:
        Most_watched_TV_shows['Votes'].append("-")
    else:
        Most_watched_TV_shows['Votes'].append(i.text)

        
        
Most_watched_TV_shows =pd.DataFrame(Most_watched_TV_shows)
Most_watched_TV_shows

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,835,393"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"874,161"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"879,319"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"264,212"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"225,709"
5,Orange Is the New Black,(2013–2019),"Comedy, Crime, Drama",59 min,8,"283,523"
6,Riverdale,(2017– ),"Crime, Drama, Mystery",45 min,6.8,"125,076"
7,Grey's Anatomy,(2005– ),"Drama, Romance",41 min,7.5,"263,661"
8,The Flash,(2014– ),"Action, Adventure, Drama",43 min,7.6,"316,948"
9,Arrow,(2012–2020),"Action, Adventure, Crime",42 min,7.5,"413,424"
10,Money Heist,(2017–2021),"Action, Crime, Mystery",70 min,8.3,"337,414"
11,The Big Bang Theory,(2007–2019),"Comedy, Romance",22 min,8.1,"740,421"
12,Black Mirror,(2011– ),"Drama, Sci-Fi, Thriller",60 min,8.8,"466,004"
13,Sherlock,(2010–2017),"Crime, Drama, Mystery",88 min,9.1,"834,669"
14,Vikings,(2013–2020),"Action, Adventure, Drama",44 min,8.5,"455,512"
15,Pretty Little Liars,(2010–2017),"Drama, Mystery, Romance",44 min,7.4,"155,225"
16,The Vampire Diaries,(2009–2017),"Drama, Fantasy, Horror",43 min,7.7,"292,045"
17,American Horror Story,(2011– ),"Drama, Horror, Thriller",60 min,8,"283,971"
18,Breaking Bad,(2008–2013),"Crime, Drama, Thriller",49 min,9.4,"1,539,328"
19,Lucifer,(2016– ),"Crime, Drama, Fantasy",42 min,8.1,"258,797"
20,Supernatural,(2005–2020),"Drama, Fantasy, Horror",44 min,8.4,"401,760"
21,Prison Break,(2005–2017),"Action, Crime, Drama",44 min,8.3,"490,116"
22,How to Get Away with Murder,(2014–2020),"Crime, Drama, Mystery",43 min,8.1,"135,168"
23,Teen Wolf,(2011–2017),"Action, Drama, Fantasy",41 min,7.6,"132,021"
24,The Simpsons,(1989– ),"Animation, Comedy",22 min,8.6,"373,713"
25,Once Upon a Time,(2011–2018),"Adventure, Fantasy, Romance",60 min,7.7,"211,935"
26,Narcos,(2015–2017),"Biography, Crime, Drama",49 min,8.8,"373,001"
27,Daredevil,(2015–2018),"Action, Crime, Drama",54 min,8.6,"372,850"
28,Friends,(1994–2004),"Comedy, Romance",22 min,8.9,"872,451"
29,How I Met Your Mother,(2005–2014),"Comedy, Romance",22 min,8.3,"621,130"
...,...,...,...,...,...,...
70,Under the Dome,(2013–2015),"Drama, Mystery, Sci-Fi",43 min,6.6,"102,393"
71,The Umbrella Academy,(2019– ),"Action, Adventure, Comedy",60 min,8,"173,337"
72,True Detective,(2014–2019),"Crime, Drama, Mystery",55 min,8.9,"512,923"
73,The OA,(2016–2019),"Drama, Fantasy, Mystery",60 min,7.8,"94,109"
74,Desperate Housewives,(2004–2012),"Comedy, Drama, Mystery",45 min,7.5,"119,184"
75,Better Call Saul,(2015– ),"Crime, Drama",46 min,8.8,"344,466"
76,Bates Motel,(2013–2017),"Drama, Horror, Mystery",45 min,8.1,"99,765"
77,The Punisher,(2017–2019),"Action, Crime, Drama",53 min,8.5,"193,013"
78,Atypical,(2017–2021),"Comedy, Drama",30 min,8.3,"66,365"
79,Dynasty,(2017– ),Drama,42 min,7.3,"16,400"
80,This Is Us,(2016–2022),"Comedy, Drama, Romance",45 min,8.7,"115,454"
81,The Good Place,(2016–2020),"Comedy, Drama, Fantasy",22 min,8.2,"125,759"
82,Iron Fist,(2017–2018),"Action, Adventure, Crime",55 min,6.5,"118,098"
83,The Rain,(2018–2020),"Drama, Sci-Fi, Thriller",45 min,6.3,"32,583"
84,Mindhunter,(2017–2019),"Crime, Drama, Thriller",60 min,8.6,"233,119"
85,Revenge,(2011–2015),"Drama, Mystery, Thriller",44 min,7.8,"114,469"
86,Luke Cage,(2016–2018),"Action, Crime, Drama",55 min,7.3,"119,541"
87,Scandal,(2012–2018),"Drama, Thriller",43 min,7.7,"68,465"
88,The Defenders,(2017),"Action, Adventure, Crime",50 min,7.3,"93,919"
89,Big Little Lies,(2017–2019),"Crime, Drama, Mystery",60 min,8.5,"166,664"
90,Insatiable,(2018–2019),"Comedy, Drama, Thriller",45 min,6.5,"23,880"
91,The Mentalist,(2008–2015),"Crime, Drama, Mystery",43 min,8.1,"169,475"
92,The Crown,(2016– ),"Biography, Drama, History",58 min,8.6,"167,935"
93,Chernobyl,(2019),"Drama, History, Thriller",330 min,9.4,"589,235"
94,iZombie,(2015–2019),"Comedy, Crime, Drama",42 min,7.8,"61,902"
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,790"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,397"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"169,584"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,120"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"193,351"

10. Details of Datasets from UCI machine learning repositories. 
      Url = https://archive.ics.uci.edu/ 
      You have to find the following details: 
A) Dataset name 
B) Data type 
C) Task 
D) Attribute type 
E) No of instances 
F) No of attribute 
G) Year 
Note: - from the home page you have to go to the Show All Dataset page through code.

In [10]:
# Accessing chrome browser
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)

driver.get("https://archive.ics.uci.edu/")
time.sleep(4)


action = ActionChains(driver)
view = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td/span/b/a")
action.click(view).perform()
time.sleep(5)

ML_repo = {}
ML_repo['Dataset name']= []
ML_repo['Data type'] = []
ML_repo['Task'] = []
ML_repo['Attribute type'] = []
ML_repo['No of instances'] = []
ML_repo['No of attribute'] = []
ML_repo['Year'] = []


# Scraping the required detail

name = driver.find_elements_by_xpath("//p[@class='normal']/b/a")
for i in name:
    if len(ML_repo['Dataset name']) < 586:
        ML_repo['Dataset name'].append(i.text)
    else:
        pass
     
time.sleep(1)
for i in range(2,588):
    dtype = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
    if dtype.text == " ":
        ML_repo['Data type'].append("-")
    else:
        ML_repo['Data type'].append(dtype.text)
    
    task = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
    if task.text == " ":
        ML_repo['Task'].append("-")
    else:
        ML_repo['Task'].append(task.text) 
        
    type = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
    if type.text == " ":
        ML_repo['Attribute type'].append("-")
    else:
        ML_repo['Attribute type'].append(type.text)
        
    instance = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
    if instance.text == " ":
        ML_repo['No of instances'].append("-")
    else:
        ML_repo['No of instances'].append(instance.text) 
        
    num_attribute = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
    if num_attribute.text == " ":
        ML_repo['No of attribute'].append("-")
    else:
        ML_repo['No of attribute'].append(num_attribute.text)        
        
    year = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
    if year.text == " ":
        ML_repo['Year'].append("-")
    else:
        ML_repo['Year'].append(year.text)
time.sleep(1)


#Creating Dataframe
ML_repo = pd.DataFrame(ML_repo)
ML_repo.to_csv("ML_repo.csv")
ML_repo.head(20)

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,-
3,Anonymous Microsoft Web Data,-,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
5,Artificial Characters,Multivariate,Classification,"Categorical, Integer, Real",6000,7,1992
6,Audiology (Original),Multivariate,Classification,Categorical,226,-,1987
7,Audiology (Standardized),Multivariate,Classification,Categorical,226,69,1992
8,Auto MPG,Multivariate,Regression,"Categorical, Real",398,8,1993
9,Automobile,Multivariate,Regression,"Categorical, Integer, Real",205,26,1987
10,Badges,"Univariate, Text",Classification,-,294,1,1994
11,Balance Scale,Multivariate,Classification,Categorical,625,4,1994
12,Balloons,Multivariate,Classification,Categorical,16,4,-
13,Breast Cancer,Multivariate,Classification,Categorical,286,9,1988
14,Breast Cancer Wisconsin (Original),Multivariate,Classification,Integer,699,10,1992
15,Breast Cancer Wisconsin (Prognostic),Multivariate,"Classification, Regression",Real,198,34,1995
16,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569,32,1995
17,Pittsburgh Bridges,Multivariate,Classification,"Categorical, Integer",108,13,1990
18,Car Evaluation,Multivariate,Classification,Categorical,1728,6,1997
19,Census Income,Multivariate,Classification,"Categorical, Integer",48842,14,1996